services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./backend/logs:/app/backend/logs
      - ./src:/app/src
    env_file:
      - backend/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3 