[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
startCommand = "python run.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHON_VERSION = "3.11"
PYTHONPATH = "/app"

[service]
healthcheckPath = "/health"
healthcheckTimeout = 30

[service.domains]
primary = "dealsight.co"