services:
  # Backend service configuration
  - type: web
    name: dealsight-backend
    env: docker
    region: oregon
    plan: starter
    branch: render-deploy
    healthCheckPath: /health
    envVars:
      # Supabase Configuration
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      
      # Email Service
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        value: alerts@dealsight.co
      
      # Scraping Services
      - key: SERPAPI_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SCRAPER_API_KEY
        sync: false
      
      # Application Settings
      - key: PORT
        value: 5000
      - key: ENVIRONMENT
        value: production
      - key: PYTHONPATH
        value: /app
      
      # Scheduler Settings
      - key: SCRAPER_SCHEDULE
        value: "0 1 * * *"
      - key: NEWSLETTER_CHECK_INTERVAL
        value: "0 * * * *"

    # Build and start commands are in Dockerfile
    dockerCommand: gunicorn --bind 0.0.0.0:5000 run:app
    
    # Domain configuration
    domains:
      - dealsight.co

    # Health check configuration
    healthCheck:
      httpPath: /health
      port: 5000
      initialDelaySeconds: 30
      periodSeconds: 60